sudo: false
language: go
go:
- 1.10.2
install:
- scripts/bootstrap
before_script:
- export PATH="$PATH:$HOME/bin:$GOPATH/bin:$TRAVIS_BUILD_DIR/bin"
- scripts/install
script:
- scripts/test
before_deploy:
- scripts/dist
deploy:
  provider: releases
  api_key:
    secure: dsGPkfGUp83UWl4s+v9pAtS7UCFemOGCsWYr8Lm4ktL37YTVuCJmoogNiZjc941HxJ1l3ZTrWxj2tUFi/18g95ZllihhlxhbS3Imi/0YCMgXBJHpj9udOLSC7BTfzN22vowHbzdoqzwDDtusWsOCmzEyB8/eR2B6wdLqjWyY4c1IcsFzgE01CcDsAEcLs4sDVuefOX7NuOr9x8MOrPSWs9IwIa7prwkWJ7DhZGi/m0YS/lrHm6mLKuqVASu/2ent6/NabJahzeSkARZmCVeSVO0uChkbAHww12Wgti7liJCaZqiXmLGoBQpIPKsc6JWBE9Xz/HT1M6do8lCudcQ2uy48VCOFX72D1t1Cx2YP+ZaU7gYQA8vj6QU1DvMClIi5LxVxdQmxMI4UxxnW7MpJYftDEGAdBELpEgyJSSkvVRYdTYL6CYNbTNBCFxqsyNUUcDzg3lyPm8sqa5OEOUGQSAy6qK35nwICNlHxXQTpdXZcktEJ6d5+khLuvd01Etcn1TLu4WJbqQ6x92Vgsjrxecxsv9JHYNoqWEfrZU0Br1X6VogRmA6rNqowe6+ZBAwyOWFSZWvvhC6OAsmKlD2RredQxrQ0cY6uYMKSkxqrdBUiiunZKmd9RCrtDarIfYIopyHipiE5RZ50Guk3s6332nUO1O1DsYzQPpTUW89nq0w=
  file_glob: true
  file: 'dist/*.tar.gz'
  skip_cleanup: true
  on:
    repo: git-duet/git-duet
    tags: true
notifications:
  email: jesse.szwedko@gmail.com
